# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger
  PLATFORM_DEV:
    - 2.3
    - 2.4
    - 2.5

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php56-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  visreg:
    image: backstopjs/backstopjs
    entrypoint: [ "/bin/bash" ]
    environment:
      - TERM=xterm
      
# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php56-dev
    group: setup
    commands:
      - PROJECT=$(pwd) composer toolkit-install
      - rm -rf ./.tmp/ ./build
      - cp ./includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  tunnel:
    image: fpfis/drone-frpc-plugin:latest
    group: setup
    detach: true
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/toolkit/.frpc

  # ============================================================================
  # Build section:
  # ============================================================================
  build:
    image: fpfis/php56-dev
    group: build
    commands:
      - ./toolkit/phing build-platform build-subsite-dev -D'platform.package.version'='${PLATFORM_DEV}' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  solr:
    image: fpfis/solr5
    group: build
    detach: true

  # ============================================================================
  # Install section:
  # ============================================================================
  visreg-init:
    image: backstopjs/backstopjs
    commands:
      - cp -f includes/docker/docker-backstopjs/runPuppet.js /usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js
      - export TERM=xterm; backstop init

  install-clean:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clean ${PHING_OPTS}
      - ./toolkit/phing drush-gdpr-dump -D'database-file'='/test/toolkit/dump.sql' ${PHING_OPTS}
      - ./toolkit/phing docker-backstop-generate ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  visreg-before:
    image: backstopjs/backstopjs
    commands:
      - export TERM=xterm; backstop reference

  # ============================================================================
  # Clone section:
  # ============================================================================
  install-clone:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clone -D'project.db.file'='/test/toolkit/dump.sql' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  visreg-after:
    image: backstopjs/backstopjs
    commands:
      - export TERM=xterm; backstop test

  selenium:
    image: selenium/standalone-chrome
    group: prebehat
    detach: true

  # ============================================================================
  # Test section:
  # ============================================================================
  behat:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing drush-settings-generate test-run-behat -D'project.url.base'='$${behat.base_url}' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Notify section:
  # ============================================================================
  slack:
    image: plugins/slack
    channel: ci
    username: Subsite-QA
    icon_url: https://www.drupal.org/files/examples_meatwad256.png
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|passed> all subsite tests.
      {{else}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|failed> subsite tests.
      {{/success}}
