# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php71-build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php71-build
    commands:
      - composer install --ansi
      - rm -rf /var/www/html
      - mkdir -p /test/toolkit/resources/templates/drupal7/web-
      - ln -s /test/toolkit/resources/templates/drupal7/web /var/www/html
      - ./vendor/bin/run project:test-drupal7
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  tunnel:
    image: fpfis/drone-frpc-plugin:latest
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}-${DRONE_JOB_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/toolkit/.frpc
    when:
      status: [ success, failure ]
