workspace:
  base: /test
  path: toolkit

services:
  web:
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    environment:
    - DOCUMENT_ROOT=/test/toolkit

pipeline:
  composer-install:
    group: prepare
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    volumes:
    - /cache:/cache
    commands:
    - composer install --ansi --no-suggest --no-progress

  grumphp:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    commands:
    - ./vendor/bin/grumphp run
  
  phpunit:
    group: test
    image: ${IMAGE_PHP=fpfis/httpd-php-dev:7.1}
    commands:
    - ./vendor/bin/phpunit

matrix:
  IMAGE_PHP:
  - fpfis/httpd-php-dev:7.1
