# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  TEMPLATE:
    - drupal7
    - drupal8
    - platform
  PHP_VERSION:
#    - 56
    - 71

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  toolkit:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - composer install --ansi --no-suggest
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  template:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run toolkit:setup-template --template=${TEMPLATE} --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  install:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - /usr/bin/env PHP_OPTIONS="-d sendmail_path=`which true`" ./vendor/bin/run drupal:site-install --working-dir=/test/toolkit/template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  phpcs:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run drupal:phpcs --working-dir=/test/toolkit/template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  behat:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run drupal:core-behat --working-dir=/test/toolkit/template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]
      # Temporarily disable behat on platform.
      matrix:
        TEMPLATE: [ drupal7, drupal8 ]

  enable:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run drupal:enable-all --working-dir=/test/toolkit/template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  data:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run drupal:generate-data --working-dir=/test/toolkit/template --ansi --progress-delay=300
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]