# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php71-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php71-build
    commands:
      - composer install --ansi --no-suggest
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Test D7 section:
  # ============================================================================
  test-drupal7:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run project:test-drupal7 --ansi
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache