workspace:
  base: /test
  path: toolkit

matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger
  PLATFORM_DEV:
    - 2.3
    - 2.4
    - 2.5

services:
  web:
    image: fpfis/php56-dev
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build

pipeline:

  # Install toolkit and load drone props.
  setup:
    image: fpfis/php56-dev
    group: setup
    commands:
      - PROJECT=$(pwd) composer toolkit-install
      - rm -rf ./.tmp/ ./build
      - cp ./includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # Start tunnel for easy access to build.
  tunnel:
    image: fpfis/drone-frpc-plugin:latest
    group: setup
    detach: true
    secrets: [ frpc_token, frpc_server ]
    environment:
      - PLUGIN_ENDPOINT=web:8080
      - PLUGIN_GEN_AUTH=yes
      - PLUGIN_DOMAIN=${DRONE_REPO_NAME}-${DRONE_BUILD_NUMBER}.ci.fpfis.tech.ec.europa.eu
      - PLUGIN_URL_OUTPUT_FILE=/test/toolkit/.frpc

  # Build platform and subsite.
  build:
    image: fpfis/php56-dev
    group: build
    commands:
      - ./toolkit/phing build-platform build-subsite-dev -D'platform.package.version'='${PLATFORM_DEV}' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # Start solr in detached mode in preperation for install.
  solr:
    image: fpfis/solr5
    group: build
    detach: true

  # Start clean installation of subsite.
  install-clean:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clean -D'project.url.base'="$(cat /test/toolkit/.frpc)" ${PHING_OPTS}
      - ./toolkit/phing drush-sql-dump -D'database-file'='/test/toolkit/dump.sql' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # Run backtrac snapshot of build (always green)
  visreg-before:
    image: fpfis/php56-build
    secrets: [ BACKTRAC_TOKEN, BACKTRAC_DYNAMIC_PROJECT_ID ]
    commands:
      - ./toolkit/phing drush-settings-generate test-run-backtrac -D'project.url.base'="$(cat /test/toolkit/.frpc)" -D'backtrac.secure'='false' -D'backtrac.token'=$${BACKTRAC_TOKEN} -D'project.backtrac.id'=$${BACKTRAC_DYNAMIC_PROJECT_ID} -D'backtrac.env'='development' -D'backtrac.compare.mode'='snapshot' ${PHING_OPTS} || return 0

  # Start clone installation of subsite.
  install-clone:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clone -D'project.db.file'='/test/toolkit/dump.sql' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # Run backtrac self compare of build (may not be accurate):
  # Possible that it starts comparing against another build.
  # TODO: solve with better thing. (always green)
  visreg-after:
    image: fpfis/php56-build
    group: prebehat
    secrets: [ BACKTRAC_TOKEN, BACKTRAC_DYNAMIC_PROJECT_ID ]
    commands:
      - ./toolkit/phing drush-settings-generate test-run-backtrac -D'project.url.base'="$(cat /test/toolkit/.frpc)" -D'backtrac.secure'='false' -D'backtrac.token'=$${BACKTRAC_TOKEN} -D'project.backtrac.id'=$${BACKTRAC_DYNAMIC_PROJECT_ID} -D'backtrac.env'='development' -D'backtrac.compare.mode'='compare_itself' ${PHING_OPTS} || return 0

  # Start selenium in detached mode for behat usage.
  selenium:
    image: selenium/standalone-chrome
    group: prebehat
    detach: true

  # Run default behat tests.
  behat:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing drush-settings-generate test-run-behat -D'project.url.base'='$${behat.base_url}' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # Send notification to slack.
  slack:
    image: plugins/slack
    channel: ci
    username: Subsite-QA
    icon_url: https://www.drupal.org/files/examples_meatwad256.png
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|passed> all subsite tests.
      {{else}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|failed> subsite tests.
      {{/success}}
