# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger
  VERSION:
    - 2.3
    - 2.4
    - 2.5
    - 2.5
    - 2.5
  PROFILE:
    - multisite_drupal_standard
    - multisite_drupal_standard
    - multisite_drupal_standard
    - drupal
    - drupal
  PROFILE_CORE:
    - 7.*
    - 7.*
    - 7.*
    - 7.*
    - 8.*
  PROFILE_NAME:
    - MULTISITE_STANDARD_DRUPAL
    - MULTISITE_STANDARD_DRUPAL
    - minimal
    - minimal
    - minimal
# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php56-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  visreg:
    image: backstopjs/backstopjs
    entrypoint: [ "/bin/bash" ]
      
# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php56-dev
    group: setup
    commands:
      - PROJECT=$(pwd) composer toolkit-install
      - rm -rf ./.tmp/ ./build
      - cp ./includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Build section:
  # ============================================================================
  build:
    image: fpfis/php56-dev
    group: build
    commands:
      - ./toolkit/phing build-platform build-subsite-dev -D'platform.package.version'='${VERSION}' -D'profile'='${PROFILE}' -D'profile.name'='${PROFILE_NAME}' -D'profile.core'='${PROFILE_CORE}' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  solr:
    image: fpfis/solr5
    group: build
    detach: true

  # ============================================================================
  # Install section:
  # ============================================================================
  visreg-init:
    image: backstopjs/backstopjs
    commands:
      - backstop init

  install-clean:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clean ${PHING_OPTS}
      - ./toolkit/phing docker-backstop-generate ${PHING_OPTS}
      - ./toolkit/phing drush-gdpr-dump -D'database-file'='/test/toolkit/dump.sql' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  visreg-before:
    image: backstopjs/backstopjs
    commands:
      - cp -f includes/docker/docker-backstopjs/core/util/runPuppet.js /usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js
      - cp -f includes/docker/docker-backstopjs/core/util/compare/index.js /usr/local/lib/node_modules/backstopjs/core/util/compare/index.js
      - backstop reference

  # ============================================================================
  # Clone section:
  # ============================================================================
  install-clone:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clone -D'project.db.file'='/test/toolkit/dump.sql' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  visreg-after:
    image: backstopjs/backstopjs
    commands:
      - cp -f includes/docker/docker-backstopjs/core/util/runPuppet.js /usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js
      - cp -f includes/docker/docker-backstopjs/core/util/compare/index.js /usr/local/lib/node_modules/backstopjs/core/util/compare/index.js
      - backstop test || echo 'Proceed ...'

  smoketest:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing drush en -y dblog ${PHING_OPTS}
      - ./toolkit/phing drush-run-smoketest ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  selenium:
    image: selenium/standalone-chrome
    group: prebehat
    detach: true

  # ============================================================================
  # Test section:
  # ============================================================================
  behat:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing drush-settings-generate test-run-behat -D'project.url.base'='$${behat.base_url}' ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Notify section:
  # ============================================================================
  slack:
    image: plugins/slack
    channel: ci
    username: Subsite-QA
    icon_url: https://www.drupal.org/files/examples_meatwad256.png
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|passed> all subsite tests.
      {{else}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|failed> subsite tests.
      {{/success}}
