# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  COMPOSER_TEMPLATE:
    - drupal7
    - drupal8
    - platform
  PHP_VERSION:
    - 56
    - 71
  DRUPAL_PROFILE:
    - standard
    - multisite_drupal_standard
    - multisite_drupal_communities
  # Temporarily added to skip builds.
  include:
    - COMPOSER_TEMPLATE: drupal7
      DRUPAL_PROFILE: standard
      PHP_VERSION: 71
    - COMPOSER_TEMPLATE: drupal8
      DRUPAL_PROFILE: standard
      PHP_VERSION: 71
    - COMPOSER_TEMPLATE: platform
      DRUPAL_PROFILE: multisite_drupal_standard
      PHP_VERSION: 71
  RUNNER_OPTS:
    - "--ansi --progress-delay=300"

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - composer install --ansi --no-suggest
      - ln -sf $(pwd)/runner.yml $(pwd)/resources/drupal/${COMPOSER_TEMPLATE}/runner.yml
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  install:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run --working-dir=$(pwd)/resources/drupal/${COMPOSER_TEMPLATE} project:install -o drupal.site.profile: ${DRUPAL_PROFILE} ${RUNNER_OPTS}
      - rm -rf build && ln -sf $(pwd)/resources/drupal/${COMPOSER_TEMPLATE}/web build
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  phpcs:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run project:phpcs --working-dir=$(pwd)/resources/drupal/${COMPOSER_TEMPLATE} ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  smoke:
    image: fpfis/php71-build
    commands:
      - ./vendor/bin/run project:smoke --working-dir=$(pwd)/resources/drupal/${COMPOSER_TEMPLATE} ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache