# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  COMPOSER_TEMPLATE:
    - drupal7
    - drupal8
    - platform
  PHP_VERSION:
    - 56
    - 71
  DRUPAL_PROFILE:
    - standard
    - multisite_drupal_standard
    - multisite_drupal_communities
  RUNNER_OPTS:
    - "--ansi --progress-delay=300"
  # Temporarily added to skip builds.
  include:
    - COMPOSER_TEMPLATE: drupal7
      DRUPAL_PROFILE: standard
      PHP_VERSION: 71
    # - COMPOSER_TEMPLATE: drupal8
    #   DRUPAL_PROFILE: standard
    #   PHP_VERSION: 71
    # - COMPOSER_TEMPLATE: platform
    #   DRUPAL_PROFILE: multisite_drupal_standard
    #   PHP_VERSION: 71

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - composer install --ansi --no-suggest
      - ln -sf $(pwd)/runner.yml $(pwd)/resources/drupal/${COMPOSER_TEMPLATE}/runner.yml
      - rm -rf build && ln -sf $(pwd)/resources/drupal/${COMPOSER_TEMPLATE}/web build
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  install:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - cd resources/drupal/${COMPOSER_TEMPLATE}
      - ./vendor/bin/run project:install ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  phpcs:
    image: fpfis/php71-build
    commands:
      - cd resources/drupal/${COMPOSER_TEMPLATE}
      - ./vendor/bin/run project:phpcs ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status:  [ failure, success ]

  behat:
    image: fpfis/php71-build
    commands:
      - cd resources/drupal/${COMPOSER_TEMPLATE}
      - ./vendor/bin/run drupal:core-behat ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status:  [ failure, success ]

  enable:
    image: fpfis/php71-build
    commands:
      - cd resources/drupal/${COMPOSER_TEMPLATE}
      - ./vendor/bin/run drupal:enable-all ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status:  [ failure, success ]

  data:
    image: fpfis/php71-build
    commands:
      - cd resources/drupal/${COMPOSER_TEMPLATE}
      - ./vendor/bin/run project:generate-data ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status:  [ failure, success ]