workspace:
  base: /test
  path: toolkit

matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger
services:
  web:
    image: fpfis/php56-dev
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
      - TOOLKIT_ENV_PROPS=/test/toolkit/includes/phing/props/docker.props
  mysql:
    image: fpfis/mysql56
  selenium:
    image: selenium/standalone-chrome
    environment:
      - SE_OPTS=-log /tmp/selenium.log
  solr:
    image: fpfis/solr5

pipeline:
  toolkit:
    image: fpfis/php56-dev
    commands:
      - PROJECT=$(pwd) composer toolkit-install
      - ./toolkit/phing project-properties-validate ${PHING_OPTS}
    volumes:
      - /cache:/cache

  build:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing build-platform ${PHING_OPTS}
      - ./toolkit/phing build-subsite-dev ${PHING_OPTS}
    volumes:
      - /cache:/cache
      - /cache/share:/tmp/toolkit

  install:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clean ${PHING_OPTS}
    volumes:
      - /cache:/cache
      - /cache/share:/tmp/toolkit

  test:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing test-run-behat ${PHING_OPTS}
    volumes:
      - /cache:/cache
