# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  TEMPLATE:
    - drupal7
    - drupal8
    - platform
  PHP_VERSION:
    - 56
    - 71
  DRUPAL_PROFILE:
    - standard
    - multisite_drupal_standard
    - multisite_drupal_communities
  RUNNER_OPTS:
    - "--ansi --progress-delay=300"
  # Temporarily added to skip builds.
  include:
    - TEMPLATE: drupal7
      DRUPAL_PROFILE: standard
      PHP_VERSION: 71
    - TEMPLATE: drupal8
      DRUPAL_PROFILE: standard
      PHP_VERSION: 71
    - TEMPLATE: platform
      DRUPAL_PROFILE: multisite_drupal_standard
      PHP_VERSION: 71

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.7
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  selenium:
    image: selenium/standalone-chrome

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  toolkit:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - composer install --ansi --no-suggest
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  template:
    image: fpfis/php${PHP_VERSION}-build
    commands:
      - ./vendor/bin/run toolkit:setup-template --template=${TEMPLATE} ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  install:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      WORKDIR: /test/toolkit/resources/drupal/${TEMPLATE}
    commands:
      - ./vendor/bin/run drupal:install ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  phpcs:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      WORKDIR: /test/toolkit/resources/drupal/${TEMPLATE}
    commands:
      - ./vendor/bin/run drupal:phpcs ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  behat:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      WORKDIR: /test/toolkit/resources/drupal/${TEMPLATE}
    commands:
      - ./vendor/bin/run drupal:core-behat ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  enable:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      WORKDIR: /test/toolkit/resources/drupal/${TEMPLATE}
    commands:
      - ./vendor/bin/run drupal:enable-all ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]

  data:
    image: fpfis/php${PHP_VERSION}-build
    environment:
      WORKDIR: /test/toolkit/resources/drupal/${TEMPLATE}
    commands:
      - ./vendor/bin/run drupal:generate-data ${RUNNER_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
    when:
      status: [ failure, success ]