workspace:
  base: /test
  path: ssk

services:
  web:
    image: fpfis/php56-dev
    environment:
     - DOCUMENT_ROOT=/test/ssk/build
  mysql:
    image: fpfis/mysql56
  selenium:
    image: selenium/standalone-chrome
    environment:
      - SE_OPTS=-log /tmp/selenium.log
  solr:
    image: fpfis/solr5

pipeline:
  toolkit:
    image: fpfis/php56-dev
    commands:
      - PROJECT=$(pwd) composer ssk-install
    volumes:
      - /cache:/cache

  build:
    image: fpfis/php56-dev
    commands:
      - ./ssk/phing project-build-platform
      - ./ssk/phing build-subsite-dev
    volumes:
      - /cache:/cache

  install:
    image: fpfis/php56-dev
    environment:
     - ASDA_PASS=${ASDA_PASS}
    commands:
      - ./ssk/phing install-project-clone -D'project.id'='belgium' -D'db.dl.username'='belgium' -D'db.dl.password'={{ASDA_PASS}}
    volumes:
      - /cache:/cache

  test:
    image: fpfis/php56-dev
    commands:
      - ./ssk/phing test-run-behat
    volumes:
      - /cache:/cache

