# ==============================================================================
# Pull request clone ===========================================================
# ==============================================================================
# Use plugin to checkout pull requests for caching issue:
# https://github.com/drone/drone/issues/2390
# ==============================================================================
clone:
  git:
    image: plugins/git:next

# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger
  BUILD_OPTIONS:
    - -D'platform.package.version'='2.3' -D'profile'='multisite_drupal_standard'
    - -D'platform.package.version'='2.4' -D'profile'='multisite_drupal_standard'
    - -D'platform.package.version'='2.5' -D'profile'='multisite_drupal_standard'
    - -D'profile'='drupal' -D'profile.name'='minimal' -D'profile.core'='7.x'
    - -D'profile'='drupal' -D'profile.name'='standard' -D'profile.core'='8.7.x'

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php56-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/build
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
  visreg:
    image: backstopjs/backstopjs
    entrypoint: [ "/bin/bash" ]

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php56-dev
    group: setup
    commands:
      - PROJECT=$(pwd) composer toolkit-install
      - rm -rf ./.tmp/ ./build
      - cp ./includes/phing/props/drone.props build.develop.props
      - ./toolkit/phing project-properties-validate ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Build section:
  # ============================================================================
  build:
    image: fpfis/php56-dev
    group: build
    commands:
      - ./toolkit/phing build-platform build-subsite-dev ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  solr:
    image: fpfis/solr5
    group: build
    detach: true

  # ============================================================================
  # Install section:
  # ============================================================================
  visreg-init:
    image: backstopjs/backstopjs
    commands:
      - backstop init

  install-clean:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clean ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing docker-backstop-generate ${BUILD_OPTIONS} ${PHING_OPTS}
      - ./toolkit/phing drush-gdpr-dump -D'database-file'='/test/toolkit/dump.sql' ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  visreg-before:
    image: backstopjs/backstopjs
    commands:
      - cp -f includes/docker/docker-backstopjs/core/util/runPuppet.js /usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js
      - cp -f includes/docker/docker-backstopjs/core/util/compare/index.js /usr/local/lib/node_modules/backstopjs/core/util/compare/index.js
      - backstop reference

  # ============================================================================
  # Clone section:
  # ============================================================================
  install-clone:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing install-clone -D'project.db.file'='/test/toolkit/dump.sql' ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  visreg-after:
    image: backstopjs/backstopjs
    commands:
      - cp -f includes/docker/docker-backstopjs/core/util/runPuppet.js /usr/local/lib/node_modules/backstopjs/core/util/runPuppet.js
      - cp -f includes/docker/docker-backstopjs/core/util/compare/index.js /usr/local/lib/node_modules/backstopjs/core/util/compare/index.js
      - backstop test || echo 'Proceed ...'

  smoketest:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing drush-run-smoketest ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  selenium:
    image: selenium/standalone-chrome
    group: prebehat
    detach: true

  # ============================================================================
  # Test section:
  # ============================================================================
  behat:
    image: fpfis/php56-dev
    commands:
      - ./toolkit/phing test-run-behat ${BUILD_OPTIONS} ${PHING_OPTS}
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache

  # ============================================================================
  # Notify section:
  # ============================================================================
  slack:
    image: plugins/slack
    channel: ci
    username: Subsite-QA
    icon_url: https://www.drupal.org/files/examples_meatwad256.png
    secrets: [ slack_webhook ]
    when:
      status: [ success, failure ]
    template: >
      {{#success build.status}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|passed> all subsite tests.
      {{else}}
        {{repo.name}}@{{build.branch}} <{{build.link}}|failed> subsite tests.
      {{/success}}
