# ==============================================================================
# Workspace location.
# ==============================================================================
workspace:
  base: /test
  path: toolkit

# ==============================================================================
# Matrix section
# ==============================================================================
matrix:
  PHING_OPTS:
    - -logger phing.listener.AnsiColorLogger

# ==============================================================================
# Main services
# ==============================================================================
services:
  web:
    image: fpfis/php71-build
    environment:
      - DOCUMENT_ROOT=/test/toolkit/resources/templates/drupal7/web
  mysql:
    image: percona/percona-server:5.6
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes

# ==============================================================================
# Pipelines
# ==============================================================================
pipeline:

  # ============================================================================
  # Setup section:
  # ============================================================================
  setup:
    image: fpfis/php71-build
    commands:
      - composer install
      - ./vendor/bin/run project:test-drupal7
    volumes:
      - /cache/${DRONE_REPO_NAME}:/cache
