toolkit:
  project_id: 'PROJECTID'
  tmp_folder: '.tmp'
  clone:
    asda_url: 'https://webgate.ec.europa.eu/fpfis/files-for/automate_dumps'
    dumpfile: 'dump.sql'
    config_file: 'config/sync/core.extension.yml'
  build:
    dist:
      root: 'dist'
      commands: []
    dev:
      commands: []
