toolkit:
  tmp_folder: '.tmp'
  clean:
    config_file: 'config/sync/core.extension.yml'
  clone:
    asda_url: 'https://webgate.ec.europa.eu/fpfis/files-for/automate_dumps/${toolkit.project_id}'
    dumpfile: 'dump.sql'
  deploy:
    config_file: 'config/sync/core.extension.yml'
    sequence_file: '.opts.yml'
    sequence_key: 'upgrade_commands'
  install:
    clone:
      commands: []
  build:
    dist:
      root: 'dist'
      keep:
        - ${drupal.root}
        - config
        - vendor
        - composer.lock
        - composer.json
      commands: []
    dev:
      commands: []
    npm:
      packages: gulp gulp-sass gulp-concat gulp-clean-css gulp-minify
      mode: --save-dev
  test:
    behat:
      from: behat.yml.dist
      to: behat.yml
  tool:
    notifications:
      endpoint: 'https://webgate.ec.europa.eu/fpfis/qa/api/v1/notifications'
    whitelist-components:
      endpoint: 'https://webgate.ec.europa.eu/fpfis/qa/api/v1/package-reviews?version=8.x'
      blocker: true
