command:
  toolkit:
    build-dist:
      options:
        root: ${drupal.root}
        dist-root: ${toolkit.build.dist.root}
        keep: ${toolkit.build.dist.keep}
    build-dev:
      options:
        root: ${drupal.root}
