command:
  toolkit:
    build-dist:
      options:
        root: ${drupal.root}
        dist-root: ${toolkit.build.dist.root}
        keep:
          - ${drupal.root}
          - vendor
          - composer.json
          - composer.lock
    build-dev:
      options:
        root: ${drupal.root}
