command:
  toolkit:
    install-dump:
      options:
        uri: ${drupal.root}
        dumpfile: ${toolkit.clone.dumpfile}
    download-dump:
      options:
        asda-url: ${toolkit.clone.asda-url}
        asda-user: ${env.ASDA_USER}
        asda-password: ${env.ASDA_PASSWORD}
        dumpfile: ${toolkit.clone.dumpfile}
        project-id: ${toolkit.project-id}
