version: '2.1'
services:
  web:
    image: fpfis/php56-dev
    build: ./docker-php
    environment:
      DOCUMENT_ROOT: ${WORKSPACE}/build
      COMPOSER_CACHE_DIR: /var/cache/composer
      COMPOSE_PROJECT_NAME: ${COMPOSE_PROJECT_NAME}
    ports:
      - 8080
    volumes:
      - ${WORKSPACE}:${WORKSPACE}
      - /cache:/cache
      - /var/cache/composer:/var/cache/composer
      - /usr/bin/docker:/usr/bin/docker
      - /usr/bin/docker-compose:/usr/bin/docker-compose
      - /var/run/docker.sock:/var/run/docker.sock
    working_dir: ${WORKSPACE}
    links:
      - mysql:mysql
      - selenium:selenium
    expose:
      - '8080'
  mysql:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_DATABASE: ${COMPOSE_PROJECT_NAME}
      MYSQL_USER: root
      MYSQL_PASSWORD: ''
      MYSQL_ROOT_HOST: '%'
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: mysqld --max_allowed_packet=32M
    expose:
      - '3306'
  #redis:
  #  image: fpfis/redis
  #varnish:
  #  image: fpfis/nexteuropa-varnish5
  solr:
    # The following cores are available :
    # - http://127.0.0.1:8983/solr/d7_search_api
    # - http://127.0.0.1:8983/solr/d7_apachesolr
    image: fpfis/solr5
  selenium:
    image: selenium/standalone-firefox
    build: ./docker-sel
